const SingleCard = ()=>{
    return  <div  class=" rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  ">  </div>
}
const DoubleCard=()=>{
    return <div  class=" col-span-2 rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> </div>
}
const Card=()=>{
    return(
        <div>
            <h1 className="font-bold text-[30px] p-2 underline decoration-fuchsia-300 " >Project Gallery</h1>
            <div class="grid grid-cols-4 grid-rows-4 gap-3">
            <SingleCard><p>ggggggggggggdgdgd</p></SingleCard>


  {/* <div  class=" rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class=" rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="  rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="rounded-md  bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="rounded-md  bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="rounded-md  bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class=" rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div>
  <div  class="rounded-md bg-fuchsia-300   hover:bg-fuchsia-400 active:bg-fuchsia-400 drop-shadow-md p-4 flex-1 ...  "> You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:underline-offset-4 to apply the underline-offset-4 utility at only medium screen sizes and above </div> */}
</div>
        </div>
    );
}
export default Card;
